78 web chat website
Ovaday/planner-AI pull request #111
Opened 2023-04-24 17:28 UTC by Skanetdima

2023-04-24 19:25 UTC, Ovaday requested changes

2023-04-24 19:25 UTC, Ovaday commented on templates/web_chat.html
> +    <style>
Стили не должны быть внутри body

2023-04-24 19:25 UTC, Ovaday commented on templates/web_chat.html
> +<section id="hero" class="d-flex align-items-center">
Почему ID секции носит 'hero'?

2023-04-24 19:25 UTC, Ovaday commented on templates/web_chat.html
> +    <style>
Подсказка:
Добавь в base.html
`{% block styles %}{% endblock %}`

После в web_chat.html в отдельном блоке пиши 
```
{% block styles %}
<style>..........</style>
{% endblock %}
```

2023-04-24 19:25 UTC, Ovaday commented on templates/web_chat.html
> +<section id="hero" class="d-flex align-items-center">
Или точнее - почему ты оставил тестовый контент и комментарий

2023-04-24 19:28 UTC, Ovaday commented
Если ты помечаешь PR как Draft - то для меня это означает что я не должен смотреть его. Если бы это было на фирме, я бы оставил PR до пятницы. Сейчас измени его статус

2023-04-24 19:56 UTC, Skanetdima commented
Как мне назвать section?

2023-04-25 21:07 UTC, Ovaday requested changes

2023-04-25 21:07 UTC, Ovaday commented on templates/base.html
> +        {% block styles %}{% endblock %}
Стили должны быть в head, а не в body

2023-04-25 21:07 UTC, Ovaday commented on templates/index.html
> +        <i class="bi bi-envelope d-flex align-items-center"><a
Верни контент index.html как было

2023-04-25 21:07 UTC, Ovaday commented on templates/web_chat.html
> +<!-- Code below only for you to know how to style and format. -->
Убери комментарии

2023-04-25 21:07 UTC, Ovaday commented on templates/web_chat.html
> +<section id="chat" class="d-flex align-items-center">
Убери эту всю секцию

2023-04-25 21:07 UTC, Ovaday commented on templates/web_chat.html
> +<div class="chat__container">
Тут все ок

2023-04-25 21:07 UTC, Ovaday commented on templates/web_chat.html
> +{% block styles %} <style>
Тут все ок

2023-04-25 21:08 UTC, Ovaday commented
Не нужно ставить пальцы вверх, если тебе доступна кнопка Resolve, то после того как ты пофиксил что-то, нажимай ее:
![image](https://user-images.githubusercontent.com/11793534/234404388-3e683193-8d7c-43e9-9451-87686c64bbd3.png)

2023-04-30 11:57 UTC, closed without merging