79 web chat api backend
Ovaday/planner-AI pull request #122
Opened 2023-04-30 12:10 UTC by NastyaKolbina

2023-04-30 13:03 UTC, Ovaday requested changes
Fix comments, otherwise good work

2023-04-30 13:03 UTC, Ovaday commented on website/views.py
> +        # ToDo Anastasia: Retrieve here messages for the user with helpers.MessageHistoryHelpers.get_last_user_messages()
remove comments, they were only for you

2023-04-30 13:03 UTC, Ovaday commented on website/views.py
> +        json_template = {
would be better to name as an 'output_template'

2023-04-30 13:03 UTC, Ovaday commented on website/views.py
>  # No need to test if that works right now. We will check it later.
remove comments here that are for you

2023-04-30 13:03 UTC, Ovaday commented on website/views.py
> +    if user_id > 0:
by default user_id is a string

2023-04-30 16:56 UTC, Ovaday requested changes
1 fix and ok

2023-04-30 16:56 UTC, Ovaday commented on website/views.py
> +    user_id = int(kwargs.get('user_id'))
check for None first:
[http://127.0.0.1:8000/api/messages/](http://127.0.0.1:8000/api/messages/)

Should return error404 and not an exception.

2023-05-09 15:51 UTC, NastyaKolbina commented
done

вс, 30 апр. 2023 г. в 19:57, Evgenii ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> 1 fix and ok
> ------------------------------
>
> In website/views.py
> <https://github.com/Ovaday/planner-AI/pull/122#discussion_r1181262227>:
>
> >
>  def insert_message(request, *args, **kwargs):
> -    print(request)
> +    user_id = int(kwargs.get('user_id'))
>
> check for None first:
> http://127.0.0.1:8000/api/messages/
>
> Should return error404 and not an exception.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ovaday/planner-AI/pull/122#pullrequestreview-1407145742>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVVHISF7MYMS6UE3MJ3TQJ3XD2KV5ANCNFSM6AAAAAAXQ4EVOI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-05-14 09:02 UTC, Ovaday approved these changes

2023-05-14 09:05 UTC, merged